### ISSUE TITLE
Activating EasyEnter on MantisBT 1.2.19 caused a redirect on the signup process

### ISSUE THREAD

**Issue by Shielded** [mantisbt-plugins/EasyEnter#2]
When you activate EasyEnter 1.0 together with jQuery 1.11.1 users can't signup anymore. As soon as you click on the "Signup for a new account" link, it just redirects you to the login page, showing the url as followed:

http://xxx/login_page.php?return=signup_page.php

As soon as EasyEnter is deactivated it works all fine again. I verified that it doesn't has to do with the other plugin we have installed (The Poser 1.1) as it still comes up when I deactivate poser.

**Comment by fg-ok** [comment]
If you got an up to date installation of mantis please test the mantis2beta-branch (https://github.com/mantisbt-plugins/EasyEnter/tree/).
I cannot reproduce your issue there

**Comment by fg-ok** [comment]
EasyEnter master-branch was released, no more compatibility for 1.* versions
