### ISSUE TITLE
stop workin with mantis 2.9,0

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [mantisbt-plugins/EasyEnter#5]
has stop after update to mantis v. 2.9.0

**Comment by Heideachim** [comment]
Well, it does work with 2.9.0, but only ONCE!
After installation, selecting a new configuration (for 'all projects') does indeed change the displayed categories. That is what it should do.
But then, it is not possible to change this any more. Any modification in EasyEnters setup are not reflected in the input screen. Instead, it stays the way the first modification was.
De-installing EasyEnter restores the standard layout.
Installing it again switches back to the layout of the first setup, even though the configuration is still as it was in the subsequent steps.

A workaround would be to erase all configration and start from scratch again. But how do you do this?

Using: 
-EaseEnter 1.1
- MantisBT 2.9.0, Schema Version 290
- PHP 7.1.12
- 10.1.29 MariaDB

**Comment by fg-ok** [comment]
Seems to work in new branch [mantis2.10](https://github.com/mantisbt-plugins/EasyEnter/tree/mantis2.10). Give it a try!
After I will have added 1-2 more fixes, the mantis2.10 branch will become the master

**Comment by Alexandre-Bernardes** [comment]
Ok. working on with the last version and mantis 2.19
thanks
